"""initial schema

Revision ID: 9bde7b365b9c
Revises: 
Create Date: 2026-10-07 22:50:40.882561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bde7b365b9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("owner_type IN ('merchant', 'platform', 'customer')", name='ck_own_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'currency', name='uq_account_owner_currency')
    )
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('charge', 'refund', 'payout', 'fee')", name='ck_txn_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_transactions_source_event_id')
    )
    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor <> 0', name='ck_entries_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_entries_account'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_entries_transaction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_account', 'entries', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_entries_transaction', 'entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_payment',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_payment_pkc'))
    )
    op.drop_index('ix_entries_transaction', table_name='entries')
    op.drop_index('ix_entries_account', table_name='entries')
    op.drop_table('entries')
    op.drop_table('transactions')
    op.drop_table('processed_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
