"""initial schema

Revision ID: 9f1749ffd03b
Revises: 
Create Date: 2026-10-07 22:50:40.514645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f1749ffd03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash', name='uq_merchants_api_key_hash')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending', 'outbox', ['next_attempt_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('idempotency_keys',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '24 hours'"), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed')", name='ck_idem_status'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name='fk_idem_merchant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id', 'key', name='pk_idempotency_merchant_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BIGINT(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount_minor > 0 AND currency = upper(currency) AND status IN ('pending', 'settled', 'failed', 'refunded')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['merchant_id', 'idempotency_key'], ['idempotency_keys.merchant_id', 'idempotency_keys.key'], name='fk_payment_idempotency', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name='fk_payments_merchant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_merchant_created_at', 'payments', ['merchant_id', sa.literal_column('created_at DESC')], unique=False)

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_payments_updated_at
        BEFORE UPDATE ON payments
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_merchant_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_outbox_pending', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    op.drop_table('merchants')
    op.execute("DROP TRIGGER IF EXISTS trg_payments_updated_at ON payments")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # ### end Alembic commands ###
